### ISSUE TITLE
ImportError: cannot import name 'Coroutine'

### ISSUE THREAD

**Issue by ErikKalkoken** [kyb3r/dhooks#28]
Trying to run dhooks on Python 3.5.2 gives the following error:

```
  File "/home/allianceserver/venv/auth/lib/python3.5/site-packages/dhooks/client.py", line 5, in <module>
    from typing import Union, List, Optional, Coroutine
ImportError: cannot import name 'Coroutine'
```

After some research incl. [this post](https://stackoverflow.com/questions/44651115/python-typing-module-missing-the-coroutine-class-in-python-3-5) on stackoverflow it appears to be the case that the class `Coroutine` was not part of earlier versions of Python  3.5. There also does not seam to be a fix available other than upgrading to a newer Python version.

It does works with never versions of 3.5 though, e.g.  I can confirm this for 3.5.7.

Since Python 3.5.2 is the latest version that comes with the widely used Ubuntu 16.04. LTS I would suggest to update the version information accordingly. Either find out and test from witch minor version of 3.5 this app will work probably or just say you need at least 3.6 to run this app.

**Comment by Taaku18** [comment]
`typing.Coroutine` was added to Python in v3.5.3, I’ll leave this open in case want to add support for the lower versions.

**Comment by ErikKalkoken** [comment]
If anyone else needs a Discord webhooks library that runs on Python 3.5.2:
Here is library that runs on Python 3.4 through 3.8, has 100% test coverage and is fully documented.
https://pypi.org/project/dhooks-lite/

**Comment by Technetium1** [comment]
According to https://packages.debian.org/buster/python3-minimal and https://packages.ubuntu.com/focal/python3-minimal this should be a non-issue now.
